### ISSUE TITLE
Transcriptions are not being sent intermittently, options.uri is a required argument

### ISSUE THREAD

**Issue by tyler71** [amazon-connect/voicemail-for-amazon-connect#75] opened 2022-01-27 18:31 UTC
Transcriptions are not being sent in some cases.
I will call the same number twice and leave a voicemail the same way after a 5 minute period.
What I cannot figure out is why it will fail sometimes and not others.

When it works the ticket looks like this:
```text
New voicemail from +1555555555.

Voicemail Transcript:
text of the transcript

Voicemail:
```
When it fails:
```text
New voicemail from +15555555555.

Voicemail:
```

---

Cloudwatch logs for lambda Voi-ContactVoicemailStreamLa

Works:
```text
Transcribe...
```

Fails:
```text
Transcribe...
ec51b6b7-c0df-4cba-9afc-8324658e20ca	INFO	{ RequestError: Error: options.uri is a required argument
    at new RequestError (/var/task/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/task/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/task/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/task/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.init (/var/task/node_modules/request/request.js:231:17)
    at Request.RP$initInterceptor [as init] (/var/task/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/var/task/node_modules/request/request.js:127:8)
    at request (/var/task/node_modules/request/index.js:53:10)
    at transcribe.getTranscriptionJob.promise.then.e (/var/task/handler/voicemail.js:1:15043)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RequestError',
  message: 'Error: options.uri is a required argument',
  cause:
   Error: options.uri is a required argument
       at Request.init (/var/task/node_modules/request/request.js:231:31)
       at Request.RP$initInterceptor [as init] (/var/task/node_modules/request-promise-core/configure/request2.js:45:29)
       at new Request (/var/task/node_modules/request/request.js:127:8)
       at request (/var/task/node_modules/request/index.js:53:10)
       at transcribe.getTranscriptionJob.promise.then.e (/var/task/handler/voicemail.js:1:15043)
       at process._tickCallback (internal/process/next_tick.js:68:7),
  error:
   Error: options.uri is a required argument
       at Request.init (/var/task/node_modules/request/request.js:231:31)
       at Request.RP$initInterceptor [as init] (/var/task/node_modules/request-promise-core/configure/request2.js:45:29)
       at new Request (/var/task/node_modules/request/request.js:127:8)
       at request (/var/task/node_modules/request/index.js:53:10)
       at transcribe.getTranscriptionJob.promise.then.e (/var/task/handler/voicemail.js:1:15043)
       at process._tickCallback (internal/process/next_tick.js:68:7),
  options:
   { method: 'GET',
     json: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
```

**Comment by dfw100** [comment] 2022-02-07 17:04
I am resolving this one since it is not reproducible as you mentioned in our meeting. We will use internal ticket created by Chris for tracking just in case issue comes up again.

**Closed as completed by dfw100** 2022-02-07 17:04 UTC

**Comment by tombray** [comment] 2022-02-10 15:03
I just encountered the same issue. I haven't been able to get transcriptions to be sent successfully yet.

```
2022-02-10T14:50:10.475Z	78b5c8dd-d926-43dc-9ce9-08fb91b2babd	INFO	RequestError: Error: options.uri is a required argument
    at new RequestError (/var/task/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/task/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/task/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/task/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.init (/var/task/node_modules/request/request.js:231:17)
    at Request.RP$initInterceptor [as init] (/var/task/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/var/task/node_modules/request/request.js:127:8)
    at request (/var/task/node_modules/request/index.js:53:10)
    at /var/task/handler/voicemail.js:1:15615
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async /var/task/handler/voicemail.js:1:3563
    at async Promise.all (index 0)
    at async Runtime.exports.stream [as handler] (/var/task/handler/voicemail.js:1:3608) {
  cause: Error: options.uri is a required argument
      at Request.init (/var/task/node_modules/request/request.js:231:31)
      at Request.RP$initInterceptor [as init] (/var/task/node_modules/request-promise-core/configure/request2.js:45:29)
      at new Request (/var/task/node_modules/request/request.js:127:8)
      at request (/var/task/node_modules/request/index.js:53:10)
      at /var/task/handler/voicemail.js:1:15615
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 0)
      at async /var/task/handler/voicemail.js:1:3563
      at async Promise.all (index 0)
      at async Runtime.exports.stream [as handler] (/var/task/handler/voicemail.js:1:3608),
  error: Error: options.uri is a required argument
      at Request.init (/var/task/node_modules/request/request.js:231:31)
      at Request.RP$initInterceptor [as init] (/var/task/node_modules/request-promise-core/configure/request2.js:45:29)
      at new Request (/var/task/node_modules/request/request.js:127:8)
      at request (/var/task/node_modules/request/index.js:53:10)
      at /var/task/handler/voicemail.js:1:15615
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 0)
      at async /var/task/handler/voicemail.js:1:3563
      at async Promise.all (index 0)
      at async Runtime.exports.stream [as handler] (/var/task/handler/voicemail.js:1:3608),
  options: {
    method: 'GET',
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

```
