### ISSUE TITLE
Voicemail admin portal incompatible with Cloudwatch ipv6

### ISSUE THREAD

**Issue by Vigrond** [amazon-connect/voicemail-for-amazon-connect#57] opened 2021-06-12 00:53 UTC
I was having difficulty accessing Cloudwatch admin portal for voicemail ( access denied errors ).

After disabling ipv6 in Cloudwatch, these permission errors seem to have been resolved.

Guide should probably be updated.

**Comment by angelacyu** [comment] 2021-08-16 17:43
Thanks for bringing this to our attention. Will add to guide for next iteration.

**Comment by khastation** [comment] 2021-09-02 17:53
@Vigrond can you provide specific logs for your issue? we're not able to reproduce this in our environment.

**Comment by dfw100** [comment] 2021-10-04 22:44
We are closing the issue since we haven't got logs from you to look in to the issue. Please reopen the issue if needed.

**Closed as completed by dfw100** 2021-10-04 22:44 UTC
