### ISSUE TITLE
No VM-Agent.json is available

### ISSUE THREAD

**Issue by samgegr8** [amazon-connect/voicemail-for-amazon-connect#59] opened 2021-07-21 04:48 UTC
Hi Team,

Can you please provide the VM-Agent.json. Previously it was available but I dont find it now from the Administrator profile.

Thanks in advance

**Comment by angelacyu** [comment] 2021-08-16 17:31
Can you please try out "Step 4. Generate and Download Contact Flows" from the deployment guide? 
https://docs.aws.amazon.com/solutions/latest/voicemail-for-amazon-connect/deployment.html

**Comment by khastation** [comment] 2021-09-01 20:22
@samgegr8 we're unable to reproduce this issue, hence closing it for now. Please reopen if issue persists.

**Closed as completed by khastation** 2021-09-01 20:22 UTC
